language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
dist: trusty
env:
  - OCAML_VERSION=4.02 PACKAGE="mirage-console" DEPOPTS="mirage-xen xenstore xenstore_transport xen-gnt xen-evtchn shared-memory-ring"
  - OCAML_VERSION=4.03 PACKAGE="mirage-console" DEPOPTS="mirage-xen xenstore xenstore_transport xen-gnt xen-evtchn shared-memory-ring"
  - OCAML_VERSION=4.03 PACKAGE="mirage-console" DEPOPTS="xenctrl mirage-xen xenstore xenstore_transport xen-gnt xen-evtchn shared-memory-ring"
